### PR TITLE
fix(package-operator): add validation of scope during package creation/update

### LINKED ISSUE #953: Creation of `Package`/`ClusterPackage` resource should be prevented if the manifest has the wrong `scope`
**Describe the bug**
We only support the following combinations of resource type - manifest scope:
- `ClusterPackage` - `Cluster`
- `Package` - `Namespaced`

Everything else might lead to undesired behavior.

**To Reproduce**
Create a file `package.yaml` with the following contents:
```yaml
# This is WRONG! cert-manager is cluster scoped!
apiVersion: packages.glasskube.dev/v1alpha1
kind: Package
metadata:
  name: cert-manager
spec:
  packageInfo:
    name: cert-manager
    version: v1.15.1+1
```

Run `kubectl apply -f package.yaml`

**Expected behavior**
The creation should be prevented.

**Screenshots**
Creation is accepted.

**Cluster Info (please complete the following information):**
 - Type: Kubernetes
 - Version: -
 - Provider: -

**Glasskube Info (please complete the following information):**
 - Package Operator version: 0.12.1
 - CLI version:0.12.1

**Additional context**
This validation should be done by the validating admission webhook: 

https://github.com/glasskube/glasskube/blob/f9a1dfe58b3cffa2df6f2f50b4280dc29e6e8ff0/internal/webhook/package_validator.go

### PR DESCRIPTION
**Pull request by ChiragRajput101**
Closes #953 

## 📑 Description
Added scope validation for creation of Package/ClusterPackage resouces.
The only supported combinations of resource type - manifest scope:

- ClusterPackage - Cluster
- Package - Namespaced

Anything else should not lead to the creation of the resource.

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information
A check that compares the Manifest and Package's scope is added

### CODE REVIEW

File: internal/webhook/package_validator.go [hunk 1]
```diff
@@ -119,6 +119,13 @@ func (p *PackageValidatingWebhook) validateCreateOrUpdate(ctx context.Context, p
 		return err
 	}
 
+	// Scope validation
+	if (manifest.Scope == nil || *manifest.Scope == "Cluster") && pkg.IsNamespaceScoped() {
+		return errors.New("invalid scope, expected ClusterPackage but found Package")
+	} else if (manifest.Scope != nil && *manifest.Scope == "Namespaced") && !pkg.IsNamespaceScoped() {
+		return errors.New("invalid scope, expected Package but found ClusterPackage")
+	}
```
Comment (kosmoz) [inline internal/webhook/package_validator.go:127]: Please use `manifest.Scope.IsCluster()` and `manifest.Scope.IsNamespaced()`. These already include the necessary nil checks.

Comment (ChiragRajput101) [reply internal/webhook/package_validator.go]: Sure, I realized the same, yesterday after making the PR. I have now used the pre-existing checks in PackageScope.

**Review by kosmoz — APPROVED** [review]
