### PR TITLE
fix(cli): update check fails in dev environment

### LINKED ISSUE #396: Flag --skip-update-check fails in dev build
**Describe the bug**
When the flag --skip-update-check is used in cli, it should check for updates and print the update message but the flag seems to fail in dev builds.

**To Reproduce**
Use the --skip-update-check flag followed by a command
`glasskube <command> --skip-update-check=false`

**Glasskube Info (please complete the following information):**
 - Package Operator version: 0.0.4
 - CLI version: dev

### PR DESCRIPTION
**Pull request by christophenne**
Closes #396

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information
Thanks @Baalekshan for bringing this up!

### CODE REVIEW

File: internal/cliutils/checkforupdate.go [hunk 1]
```diff
@@ -27,7 +29,9 @@ func CheckForUpdate() (*string, error) {
 
 func UpdateFetch() {
 	newerVersion, err := CheckForUpdate()
-	if err == nil && newerVersion != nil {
+	if err != nil {
+		fmt.Fprintf(os.Stderr, "There was an error checking for updates: %v\n", err)
```
Comment (kosmoz) [inline internal/cliutils/checkforupdate.go:33]: I think the check should continue to fail silently, as it is not really related to what the user is doing
