### PR TITLE
fix(cli): show a different operator version warning in dev mode

### LINKED ISSUE #1121: CLI update check shows wrong version for PackageOperator
**Describe the bug**
When running the update check with the CLI, the new version for the package operator is shown as the version of the locally used CLI.

**To Reproduce**
1. Run `glasskube version --skip-update-check=false` 
2. Newest version for the PackageOperator is shown as `dev` instead of `0.17.0`
```
📣 A newer version of Glasskube is available: dev → 0.17.0
📘 Release notes: https://github.com/glasskube/glasskube/releases/tag/v0.17.0

❗ Glasskube PackageOperator needs to be updated: 0.16.0 -> dev
💡 Please run `glasskube bootstrap` again to update Glasskube PackageOperator
```

**Expected behavior**
The newest version for glasskube should be shown. Same as for the CLI.
`❗ Glasskube PackageOperator needs to be updated: 0.16.0 -> 0.17.0`

**Cluster Info (please complete the following information):**
 - Type: Kubernetes
 - Version: v1.29.2
 - Provider: kind

**Glasskube Info (please complete the following information):**
 - Package Operator version: v0.16.0
 - CLI version: dev (https://github.com/glasskube/glasskube/commit/31cfe95d2088d3c0166e04b000af4f5a315db03d)

### PR DESCRIPTION
**Pull request by Aryakoste**
Closes #1121 

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

### CODE REVIEW

File: internal/cliutils/versionutil.go [hunk 1]
```diff
@@ -15,7 +15,10 @@ func CheckPackageOperatorVersion(ctx context.Context) error {
 	if err != nil {
 		return err
 	}
-	if operatorVersion[1:] != config.Version {
+	if config.Version == "dev" && operatorVersion != "" {
```
Comment (kosmoz) [inline internal/cliutils/versionutil.go:18]: please use `config.IsDevBuild()` instead

File: internal/cliutils/versionutil.go [hunk 2]
```diff
@@ -15,7 +15,10 @@ func CheckPackageOperatorVersion(ctx context.Context) error {
...
+		fmt.Fprintf(os.Stderr, "❗ Glasskube CLI version is dev but the operator version is %s\n", operatorVersion[1:])
+	}
+	if operatorVersion[1:] != config.Version && config.Version != "dev" {
```
Comment (kosmoz) [inline internal/cliutils/versionutil.go:21]: The additional dev build check here could be removed if you use an `else if` instead.

**Review by kosmoz — CHANGES_REQUESTED** [review]

**Comment by Aryakoste** [comment]
@kosmoz changes done.
