### PR TITLE
fix(package-operator): also set `ownedPackages` when dependencies unresolved

### LINKED ISSUE #1261: Dependencies/Components not cleaned up when parent has status failed
**Describe the bug**
When uninstalling a failed namespaced package, it seems like some dependencies and/or components are not deleted, only the parent/root package is deleted.

**To Reproduce**
1. Install tracecat
2. configure it invalidly to have it in status "Failed"
3. uninstall it

The database and temporal (and therefore its components) are still in the cluster. 

**Expected behavior**
They should be cleaned up.

**Screenshots**

**Cluster Info (please complete the following information):**
 - Type: [e.g. Kubernetes, OpenShift]
 - Version: [e.g. 1.29]
 - Provider: [e.g. AWS, minikube]

**Glasskube Info (please complete the following information):**
 - Package Operator version: latest dev
 - CLI version: latest dev

### LINKED ISSUE #1316: `ownedPackages` should be set earlier
**Describe the bug**
When installing a package with a dependency, the parent package usually goes to status "Pending" until the next reconciliation. During that time, the `ownedPackages` does not contain the required package yet, so if one deletes the package during its in Pending status, the required package will not get purged (it has the `installed-as-depdency` annotation though). 

Haven't debugged it yet, but could be similar to #1261?

Fix should probably be to set the `ownedPackages` already at the first reconciliation.

### PR DESCRIPTION
**Pull request by christophenne**
Closes #1316
Closes #1261

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

### CODE REVIEW

File: internal/controller/common.go [hunk 1]
```diff
@@ -482,6 +482,8 @@ func (r *PackageReconcilationContext) ensureDependencies(ctx context.Context) bo
 		}
 	}
 
+	ownerutils.Add(&r.currentOwnedPackages, ownedPackages...)
```
Comment (kosmoz) [inline internal/controller/common.go:485]: I think we should also call `r.setShouldUpdate` here 

```suggestion
	r.setShouldUpdate(ownerutils.Add(&r.currentOwnedPackages, ownedPackages...))
```

**Review by kosmoz — APPROVED** [review]
