### PR TITLE
fix: add repoclient invalidation

### LINKED ISSUE #988: Client settings on glasskube repo client does not update cache
**Describe the bug**
When adding/updating repo URL using the repo client `glasskube repo add <repoName> <repoURL>` The client settings cache does not update automatically (perhaps only on reconciliation) leading to the `glasskube repo list` command to show a repo URL that is not actually being fetched.

@kosmoz has identified where the logic has to be added to reset repo client cache upon adding new package repositories.  
 
**To Reproduce**

**Expected behavior**
To be able to add, delete and add a new repo URL under the same repo name and to always fetch the latest configured URL. 

**Screenshots**
image (1)

**Cluster Info (please complete the following information):**
 - Type: [e.g. Kubernetes, OpenShift]
 - Version: [e.g. 1.29]
 - Provider: [e.g. AWS, minikube]

**Glasskube Info (please complete the following information):**
 - Package Operator version: [e.g. v0.0.1]
 - CLI version: [output of `glasskube --version`]

**Additional context**

### PR DESCRIPTION
**Pull request by kosmoz**
Closes #988 

## 📑 Description
This PR adds checking of the repo spec when requesting a repo client from the clientset.
When requesting via name, it checks if the repo spec has been checked in the last 30 seconds (default) and checks again if it is older than that.

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

### CODE REVIEW

File: internal/repo/client/clientset.go [hunk 1]
```diff
@@ -22,24 +23,40 @@ type defaultClientsetClient struct {
...
+	return s.lastCheckedRepoSpec.Add(maxAge).After(time.Now())
+}
+
+func (s *repoClientWithState) checkRepoSpec(repo v1alpha1.PackageRepository) bool {
+	return reflect.DeepEqual(s.repo.Spec, repo.Spec)
+}
+
 func NewClientset(pkgClient adapter.PackageClientAdapter, k8sClient adapter.KubernetesClientAdapter) RepoClientset {
-	return NewClientsetWithMaxCacheAge(pkgClient, k8sClient, 5*time.Minute)
+	return NewClientsetWithMaxCacheAge(pkgClient, k8sClient, 30*time.Second)
```
Comment (christophenne) [inline internal/repo/client/clientset.go:50]: IMHO 30 seconds is quite short. I know 5 minutes on the other hand is quite long. I think we should do #756.

**Review by christophenne — APPROVED** [review]
Works fine :+1:

File: internal/repo/client/clientset.go (hunk 1 above)
Comment (kosmoz) [reply internal/repo/client/clientset.go:50]: Ah I missed that this value is also used for invalidating the cache for the repo client (not just the repo info). I think it would make sense to allow specifying different values for both. I think 30s is reasonable for the repo info but definitely on the shorter side for the repo client

Comment (kosmoz) [reply internal/repo/client/clientset.go:50]: As for #756, I think it should be tackled in a separate PR as it seems kind of unrelated

Comment (kosmoz) [reply internal/repo/client/clientset.go]: updated, let me know what you think

Comment (christophenne) [reply internal/repo/client/clientset.go]: > As for https://github.com/glasskube/glasskube/issues/756, I think it should be tackled in a separate PR as it seems kind of unrelated

yes, that's what i meant

**Review by christophenne — APPROVED** [review]
