### PR TITLE
fix: change opener to choose first ready pod

### LINKED ISSUE #302: Package `open` can fail if target pod is not yet ready to accept connections
**Describe the bug**
We don't check if a pod is ready to accept connections before we initiate the port-forward.

**To Reproduce**
1. Install a package that has an entry-point (e.g. kubernetes-dashboard)
2. Immediately click on the Open button. 
3. See error

**Expected behavior**
The port-forward should only be initiated if the pod is ready and wait until the pod gets ready for some time (e.g. 5 seconds), else the port-forward should not be initiated and will be initiated by the next attempt.

**Screenshots**

**Cluster Info (please complete the following information):**
 - Type: Kubernetes
 - Version: v1.28.3
 - Provider: minikube

**Glasskube Info (please complete the following information):**
 - Package Operator version: v0.0.3
 - CLI version: v0.0.3

**Additional context**

Command line logs:

```
glasskube UI is available at http://localhost:8580
Installing kubernetes-dashboard...
	 |I| Forwarding from 127.0.0.1:8443 -> 8443
	 |I| Forwarding from [::1]:8443 -> 8443
	 |I| Handling connection for 8443
E0227 16:13:58.327794  511974 portforward.go:409] an error occurred forwarding 8443 -> 8443: error forwarding port 8443 to pod 19fc729545d02f7843941851518089c54ffc826361cb9d6d627b5bcfec9d5269, uid : exit status 1: 2024/02/27 15:13:58 socat[45310] E connect(5, AF=2 127.0.0.1:8443, 16): Connection refused
```

### PR DESCRIPTION
**Pull request by kosmoz**
Closes #302

## 📑 Description
This PR changes the opener to choose the first ready pod matching the services label selector, rather than simply the first one. If no pod is ready, it fails.

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

### CODE REVIEW

File: pkg/open/open.go [hunk 1]
```diff
@@ -198,7 +198,12 @@ func (o *opener) pod(ctx context.Context, service *corev1.Service) (*corev1.Pod,
 	if len(pods.Items) < 1 {
 		return nil, fmt.Errorf("no pod found for service %v", service.Name)
 	}
-	return &pods.Items[0], nil
+	for _, pod := range pods.Items {
+		if isPodReady(pod) {
```
Comment (christophenne) [inline pkg/open/open.go:202]: This could be simplified with `IsStatusConditionTrue(pod.Status.Conditions, corev1.ConditionTrue)` from `k8s.io/apimachinery/pkg/api/meta/conditions.go`

**Review by christophenne — CHANGES_REQUESTED** [review]

File: pkg/open/open.go (hunk 1 above)
Comment (kosmoz) [reply pkg/open/open.go:202]: Unfortunately not. I was surprised too, but `corev1.PodCondition` is distinct from `metav1.Condition`

**Review by christophenne — APPROVED** [review]
